### ISSUE TITLE
I dont know why I don‘t have “VAELoaderDecode” and some others

### ISSUE THREAD

**Issue by NO13Listener** [lilly1987/ComfyUI_node_Lilly#1]
![微信图片_20230323024029](https://user-images.githubusercontent.com/125913223/227005433-f6fc3f28-310e-460b-9426-0129d9bd0b3e.png)
![微信图片_20230323024040](https://user-images.githubusercontent.com/125913223/227005447-9c4a1e8c-dfb0-4d6b-b01d-209be44b9624.png)
I dont know why I don‘t have “VAELoaderDecode” ，I set in  ComfyUI\custom_nodes\ComfyUI_node_Lilly but not work

**Comment by NO13Listener** [comment]
![微信截图_20230323025130](https://user-images.githubusercontent.com/125913223/227007575-3b7c171f-21e2-4d98-b1c7-133e79a37805.png)

**Comment by lilly1987** [comment]
https://github.com/lilly1987/ComfyUI_node_Lilly/releases/tag/1.0
nothing more than this version
![2023-03-24 17 50 46](https://user-images.githubusercontent.com/20321215/227471888-695054c2-90a5-4e55-9bc5-cbfbb9fed56c.png)

![2023-03-24 17 56 33](https://user-images.githubusercontent.com/20321215/227472310-18b8cb6f-566b-4246-ad89-ee3574b02cea.png)

![2023-03-24 17 56 24](https://user-images.githubusercontent.com/20321215/227472182-77086f97-465f-4d4f-a864-18c827074ddb.png)

Check if the file exists.
That module is not mine.
![2023-03-24 17 56 02](https://user-images.githubusercontent.com/20321215/227471988-13978612-a9b9-48a0-9002-b09c3c37ea6c.png)
